/** Czyszczenie schematu
Procedura usuwujaca tabele, jeśli istnieją 
*/

DECLARE
    v_count  INT;
    v_name VARCHAR2(20);
    TYPE namesarray IS VARRAY(15) OF VARCHAR2(20);
    names    namesarray;
BEGIN
    names := namesarray('students', 'students_courses', 'courses', 'majors', 'majors_courses', 'faculties', 'lecturers', 'students_courses_grades');

    FOR i IN 1..names.count LOOP
        v_name := names(i);
        
        SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = upper(v_name);
        IF v_count = 1 THEN
            DBMS_OUTPUT.PUT_LINE('Dropping table: ' || v_name);
            EXECUTE IMMEDIATE 'DROP TABLE '|| v_name || ' CASCADE CONSTRAINTS';
        END IF;
    END LOOP;
END;

/

CREATE TABLE faculties
(
    faculty_id NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 CONSTRAINT faculties_PK PRIMARY KEY,
    name VARCHAR2 (40) NOT NULL
);

CREATE TABLE lecturers
(
    lecturer_id NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 CONSTRAINT lecturers_PK PRIMARY KEY,
    name VARCHAR2 (40) NOT NULL,
    surname VARCHAR2 (40) NOT NULL
);

CREATE TABLE majors
(
    major_id NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 CONSTRAINT majors_PK PRIMARY KEY,
    name VARCHAR2 (40) NOT NULL,
    faculty_id NUMBER NOT NULL CONSTRAINT major_faculty_fk REFERENCES faculties(faculty_id)
);

CREATE TABLE students
(
    student_id NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 CONSTRAINT students_PK PRIMARY KEY,
    name VARCHAR2 (40) NOT NULL,
    surname VARCHAR2 (40) NOT NULL,
    pesel NUMBER (11) NOT NULL,
    major_id NUMBER CONSTRAINT student_major_fk REFERENCES majors(major_id),
    is_active BOOLEAN NOT NULL
);

CREATE TABLE students_courses_grades
(
    sc_id NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 CONSTRAINT sc_PK PRIMARY KEY,
    student_id NUMBER CONSTRAINT sc_student_fk REFERENCES students(student_id),
    course_id NUMBER CONSTRAINT sc_course_fk REFERENCES courses(course_id),
    grade_id CONSTRAINT sc_course_fk REFERENCES courses(course_id)
);

CREATE TABLE majors_courses
(
    mc_id NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 CONSTRAINT mc_PK PRIMARY KEY,
    major_id NUMBER CONSTRAINT mc_major_fk REFERENCES majors(major_id),
    course_id NUMBER CONSTRAINT mc_course_fk REFERENCES courses(course_id)
);

CREATE TABLE grades
(
    grade_id NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 CONSTRAINT grades_PK PRIMARY KEY,
    grade NUMBER (2,1) CHECK(grade IN (2, 2.5, 3, 3.5, 4, 4.5, 5)),
    description VARCHAR2(20)
);